-- 🟢 BASIC SQL ANALYSIS
-- List all customers and their sales representatives.
-- Retrieve all orders with status = 'Shipped'.
-- List all products in stock, sorted by quantity.
-- Get the full name and phone number of each customer.
-- Find all employees working in the San Francisco office.

-- 🟡 INTERMEDIATE ANALYSIS
-- Total number of orders per customer.
-- Top 5 customers by total payment amount.
-- Revenue per product line.
-- List all orders placed in a specific year (e.g., 2003).
-- Show the average payment amount per customer.
-- Count the number of employees per office.
-- Find customers who haven’t made any payments.
-- Display orders with more than 20 products.
-- Find products with no orders.
-- Identify all products that are low on stock (<500 units).

-- 🔵 ADVANCED BUSINESS ANALYSIS
-- Calculate total revenue per month (monthly sales report).
-- List the top-selling products (by quantity).
-- Find the best performing sales rep by revenue.
-- Revenue generated by each office.
-- Customers with late payments.
-- Average delivery time (Order vs Shipped Date).
-- Find duplicate customer entries based on name/email.

-- 🟣 COMPLEX SQL JOINS & SUBQUERIES
-- Orders with the highest total value.
-- Which office handles the most revenue?
-- Compare revenue of two or more product lines.
-- List all customers who ordered more than one type of product line.
-- display the customer who orders more than one 
-- Identify customers who placed orders but never paid.
-- List employees who don’t manage any other employees.
-- Compare payments made vs orders placed for each customer.

-- 🔶 WINDOW FUNCTIONS / RANKING (if supported in your MySQL version)
-- Rank customers by payment amount.
-- Running total of revenue over time.
-- Customer retention rate per quarter.
-- Identify repeat customers (more than 3 order).

-- 🔺 AGGREGATIONS & KPIs
-- Total sales, average order size, and number of orders.
-- Profit margin by product (if cost is available).
-- Number of orders per status (Shipped, On Hold, etc.).
-- Total number of unique products sold.

